name: My First Workflow

on: push

jobs: 
    build_job: 
        runs-on: ubuntu-latest
        steps: 
            - name: install cowsay
              run: sudo apt-get install cowsay -y
            - name: Executing shell script
              run: cowsay -f dragon "Run for cover" >> dragon.txt
            - name: upload
              uses: actions/upload-artifact@v4
              with:
                name: my-artifact
                path: dragon.txt
    test_job: 
        needs: build_job
        runs-on: ubuntu-latest
        steps: 
            - name: download
              uses: actions/download-artifact@v5
              with:
                name: my-artifact
            - name: test
              run: grep -i "dragon" my-artifact
    deploy_job: 
        needs: test_job
        runs-on: ubuntu-latest
        steps: 
            - name: download
              uses: actions/download-artifact@v5
              with:
                name: my-artifact
            - name: read
              run: cat my-artifact
