name: My First Workflow

on: push

jobs: 
    build_job: 
        runs-on: ubuntu-latest
        steps: 
            - name: install cowsay
              run: sudo apt-get install cowsay -y
            - name: Executing shell script
              run: cowsay -f dragon "Run for cover" >> dragon.txt
            - name: sleep 
              run: sleep 30
    test_job: 
        runs-on: ubuntu-latest
        steps: 
            - name: sleep
              run: sleep 10
            - name: test
              run: grep -i "dragon" dragon.txt
    deploy_job: 
        runs-on: ubuntu-latest
        steps: 
            - name: read
              run: cat dragon.txt
            - name: echo
              run: echo Deploying..
