name: My First Workflow

on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps: 
            - name: checkout repo
              uses: actions/checkout@v5
            - name: list repo
              run: ls -ltra
            - name: Executing shell script
              run: |
                chmod +x ascii.sh
                ./ascii.sh
